"""Operation registry — auto-populated by OpRequest.__init_subclass__."""

# Import all operation modules to trigger __init_subclass__ registration
from . import add_build_log as add_build_log
from . import add_indirect_root as add_indirect_root
from . import add_multiple_to_store as add_multiple_to_store
from . import add_perm_root as add_perm_root
from . import add_signatures as add_signatures
from . import add_temp_root as add_temp_root
from . import add_to_store as add_to_store
from . import add_to_store_nar as add_to_store_nar
from . import build_derivation as build_derivation
from . import build_paths as build_paths
from . import ca_derivations as ca_derivations
from . import collect_garbage as collect_garbage
from . import ensure_path as ensure_path
from . import find_roots as find_roots
from . import is_valid_path as is_valid_path
from . import nar_from_path as nar_from_path
from . import optimise_store as optimise_store
from . import query_all_valid_paths as query_all_valid_paths
from . import query_closure as query_closure
from . import query_closure_with_info as query_closure_with_info
from . import query_derivation_output_map as query_derivation_output_map
from . import query_derivation_output_map_batch as query_derivation_output_map_batch
from . import query_missing as query_missing
from . import query_path_from_hash_part as query_path_from_hash_part
from . import query_path_info as query_path_info
from . import query_path_infos as query_path_infos
from . import query_referrers as query_referrers
from . import query_subst_path_info as query_subst_path_info
from . import query_subst_path_infos as query_subst_path_infos
from . import query_substitutable_paths as query_substitutable_paths
from . import query_valid_derivers as query_valid_derivers
from . import query_valid_paths as query_valid_paths
from . import set_options as set_options
from . import sign_path_info as sign_path_info
from . import verify_store as verify_store
from .base import OP_REGISTRY as OP_REGISTRY
