"""Operation registry — auto-populated by OpRequest.__init_subclass__."""

# Import all operation modules to trigger __init_subclass__ registration
from . import (  # noqa: F401
    add_build_log,
    add_indirect_root,
    add_multiple_to_store,
    add_perm_root,
    add_signatures,
    add_temp_root,
    add_to_store,
    add_to_store_nar,
    build_derivation,
    build_paths,
    build_paths_with_results,
    builds,
    ca_derivations,
    collect_garbage,
    ensure_path,
    find_roots,
    is_valid_path,
    maintenance,
    nar_from_path,
    optimise_store,
    queries,
    query_all_valid_paths,
    query_closure,
    query_closure_with_info,
    query_derivation_output_map,
    query_derivation_outputs_batch,
    query_missing,
    query_path_from_hash_part,
    query_path_info,
    query_path_infos,
    query_referrers,
    query_subst_path_info,
    query_subst_path_infos,
    query_substitutable_paths,
    query_valid_derivers,
    query_valid_paths,
    set_options,
    store_mutations,
    verify_store,
)
from .base import OP_REGISTRY as OP_REGISTRY
