# nanopynix-proto's source tree.
#
# Not a fragment to be spliced into a build: this derivation produces the
# complete project -- `pyproject.toml` alongside the `src/nanopynix_proto`
# that protoc generates -- so it can be handed to the Python builder as a
# plain `src` and built like any other project. Nothing in the checkout is
# `src/`; every module here comes out of a `.proto`.
#
# Generating here rather than inside the package's own build is what makes
# that possible, and it also puts the code generator in the toolchain that
# suits it. protoc runs a plugin as a *separate process* that has to import
# `betterproto2_compiler` and its whole closure; nixpkgs' `withPackages`
# arranges exactly that, whereas pyproject.nix's builders deliberately do not
# propagate, so the same thing inside the package meant hand-resolving the
# plugin's closure and re-exporting `NIX_PYPROJECT_PYTHONPATH` into a phase
# the build hook does not cover.
{
  lib,
  runCommand,
  protobuf,
  python,
}:

let
  # google/rpc/status.proto ships inside the googleapis-common-protos wheel;
  # that is the import path protoc needs for it.
  pythonEnv = python.withPackages (ps: [
    ps.betterproto2-compiler
    ps.googleapis-common-protos
  ]);
in
runCommand "nanopynix-proto-source"
  {
    src = lib.fileset.toSource {
      root = ./.;
      fileset = lib.fileset.unions [
        (lib.fileset.fileFilter (file: file.hasExt "proto") ./.)
        ./pyproject.toml
      ];
    };

    nativeBuildInputs = [
      protobuf
      pythonEnv
    ];

    passthru = { inherit pythonEnv; };
  }
  ''
    mkdir -p "$out/src/nanopynix_proto"
    cp "$src/pyproject.toml" "$out/pyproject.toml"
    # py.typed is not generated by protoc, but every module here is fully
    # annotated, so mark the package as typed for downstream consumers.
    touch "$out/src/nanopynix_proto/py.typed"

    # **No `pydantic_dataclasses` option.** That option made each message a
    # pydantic dataclass rather than a plain one, and issue #127 measured what
    # it cost: 0.254 s of import time in every process that speaks the
    # protocol, which is 57% of the generated code. Each rpc worker of
    # `worker_start="spawn"` or `"stdio"` paid it.
    #
    # It bought one thing, and one caller read it. The wire format is the same
    # either way -- the same message serialises to the same bytes -- and a
    # pydantic dataclass is not a `BaseModel`, so `model_dump` and
    # `model_validate` were absent in both variants. What it gave was a check
    # of the type at construction, which pyright already makes before the line
    # runs. `Store.collect_garbage` in `rpc/client/store.py` was the one place
    # that read the check at runtime, and it now makes that check itself.
    #
    # Do not add the option back to get validation. Write the check where the
    # value arrives, as that method does.
    protoc \
      --proto_path="$src" \
      --proto_path=${pythonEnv}/${python.sitePackages} \
      --python_betterproto2_out="$out/src/nanopynix_proto" \
      --python_betterproto2_opt=client_generation=async \
      --python_betterproto2_opt=server_generation=async \
      --python_betterproto2_opt=google_protobuf_descriptors \
      common.proto \
      store.proto \
      eval.proto \
      worker.proto \
      manager.proto \
      google/rpc/status.proto
  ''
