#pragma once

#define NANOPYNIX_NIX_VERSION "@NIX_STORE_VERSION@"
#define NANOPYNIX_NIX_VERSION_MAJOR @NANOPYNIX_NIX_VERSION_MAJOR@
#define NANOPYNIX_NIX_VERSION_MINOR @NANOPYNIX_NIX_VERSION_MINOR@
#define NANOPYNIX_NIX_VERSION_NUMBER @NANOPYNIX_NIX_VERSION_NUMBER@

#define NANOPYNIX_NIX_2_32 2032
#define NANOPYNIX_NIX_2_34 2034
#define NANOPYNIX_NIX_2_35 2035
