nanopynix_bindings.store.StorePath.__eq__:
    def __eq__(self, other: object) -> bool: ...

nanopynix_bindings.store.Store.get_store_dirs:
    def get_store_dirs(self) -> dict[str, str | None]: ...

nanopynix_bindings.store.Store.get_build_log:
    def get_build_log(self, path: StorePath) -> str | None: ...
