syntax = "proto3";

package nix.store;

import "common.proto";

service StoreService {
  rpc GetUri(GetUriRequest) returns (GetUriResponse);
  rpc GetStoreDir(GetStoreDirRequest) returns (GetStoreDirResponse);
  rpc IsValidPath(IsValidPathRequest) returns (IsValidPathResponse);
  rpc ParseStorePath(ParseStorePathRequest) returns (nix.common.StorePath);
  rpc QueryPathInfo(QueryPathInfoRequest) returns (nix.common.PathInfo);
  rpc QueryPathFromHashPart(QueryPathFromHashPartRequest) returns (QueryPathFromHashPartResponse);
  rpc ComputeFsClosure(ComputeFsClosureRequest) returns (nix.common.StorePathList);
  rpc QueryMissing(QueryMissingRequest) returns (nix.common.MissingInfo);
  rpc QueryDerivationOutputs(QueryDerivationOutputsRequest) returns (nix.common.StorePathList);
  rpc QueryValidDerivers(QueryValidDeriversRequest) returns (nix.common.StorePathList);
  rpc QueryAllValidPaths(QueryAllValidPathsRequest) returns (nix.common.StorePathList);
  rpc QueryReferrers(QueryReferrersRequest) returns (nix.common.StorePathList);
  rpc QuerySubstitutablePaths(QuerySubstitutablePathsRequest) returns (nix.common.StorePathList);
  rpc BuildPathsWithResults(BuildPathsWithResultsRequest) returns (nix.common.BuildResultList);
  rpc BuildForHumans(BuildPathsWithResultsRequest) returns (nix.common.BuildResultList);
  rpc ReadDerivation(ReadDerivationRequest) returns (nix.common.Derivation);
  rpc BuildDerivation(BuildDerivationRequest) returns (nix.common.BuildResult);
  rpc FollowLinksToStorePath(FollowLinksToStorePathRequest) returns (nix.common.StorePath);
  rpc AddTempRoot(AddTempRootRequest) returns (AddTempRootResponse);
  rpc FindRoots(FindRootsRequest) returns (FindRootsResponse);
  rpc CollectGarbage(CollectGarbageRequest) returns (CollectGarbageResponse);
  rpc AddPermRoot(AddPermRootRequest) returns (AddPermRootResponse);
  rpc AddIndirectRoot(AddIndirectRootRequest) returns (AddIndirectRootResponse);
  rpc EnsurePath(EnsurePathRequest) returns (EnsurePathResponse);
  rpc OptimiseStore(OptimiseStoreRequest) returns (OptimiseStoreResponse);
  rpc VerifyStore(VerifyStoreRequest) returns (VerifyStoreResponse);
}

message GetUriRequest {
  int64 store_handle = 100;
}
message GetUriResponse {
  string uri = 1;
}

message GetStoreDirRequest {
  int64 store_handle = 100;
}
message GetStoreDirResponse {
  string dir = 1;
}

message IsValidPathRequest {
  string path = 1;
  int64 store_handle = 100;
}
message IsValidPathResponse {
  bool valid = 1;
}

message ParseStorePathRequest {
  string path = 1;
  int64 store_handle = 100;
}

message QueryPathInfoRequest {
  string path = 1;
  int64 store_handle = 100;
}

message QueryPathFromHashPartRequest {
  string hash_part = 1;
  int64 store_handle = 100;
}
message QueryPathFromHashPartResponse {
  optional nix.common.StorePath path = 1;
}

message ComputeFsClosureRequest {
  string path = 1;
  bool flip_direction = 2;
  bool include_outputs = 3;
  bool include_derivers = 4;
  int64 store_handle = 100;
}

message QueryMissingRequest {
  repeated string paths = 1;
  int64 store_handle = 100;
}

message QueryDerivationOutputsRequest {
  string path = 1;
  int64 store_handle = 100;
}

message QueryValidDeriversRequest {
  string path = 1;
  int64 store_handle = 100;
}

message QueryAllValidPathsRequest {
  int64 store_handle = 100;
}

message QueryReferrersRequest {
  string path = 1;
  int64 store_handle = 100;
}

message QuerySubstitutablePathsRequest {
  repeated string paths = 1;
  int64 store_handle = 100;
}

message BuildPathsWithResultsRequest {
  repeated string paths = 1;
  int32 build_mode = 2;
  int64 eval_store_handle = 3;
  int64 store_handle = 100;
}

message ReadDerivationRequest {
  string path = 1;
  int64 store_handle = 100;
}

message BuildDerivationRequest {
  string path = 1;
  int32 build_mode = 2;
  int64 store_handle = 100;
}

message FollowLinksToStorePathRequest {
  string path = 1;
  int64 store_handle = 100;
}

message AddTempRootRequest {
  string path = 1;
  int64 store_handle = 100;
}
message AddTempRootResponse {}

message FindRootsRequest {
  bool censor = 1;
  int64 store_handle = 100;
}
message GCRoot {
  string link = 1;
  nix.common.StorePath path = 2;
}
message FindRootsResponse {
  repeated GCRoot roots = 1;
}

enum GCAction {
  GC_ACTION_UNSPECIFIED = 0;
  GC_ACTION_RETURN_LIVE = 1;
  GC_ACTION_RETURN_DEAD = 2;
  GC_ACTION_DELETE_DEAD = 3;
  GC_ACTION_DELETE_SPECIFIC = 4;
}

message CollectGarbageRequest {
  GCAction action = 1;
  bool ignore_liveness = 2;
  repeated string paths_to_delete = 3;
  uint64 max_freed = 4;
  int64 store_handle = 100;
}
message CollectGarbageResponse {
  repeated string paths = 1;
  uint64 bytes_freed = 2;
}

message AddPermRootRequest {
  string store_path = 1;
  string gc_root = 2;
  int64 store_handle = 100;
}
message AddPermRootResponse {
  string path = 1;
}

message AddIndirectRootRequest {
  string path = 1;
  int64 store_handle = 100;
}
message AddIndirectRootResponse {}

message EnsurePathRequest {
  string path = 1;
  int64 store_handle = 100;
}
message EnsurePathResponse {}

message OptimiseStoreRequest {
  int64 store_handle = 100;
}
message OptimiseStoreResponse {}

message VerifyStoreRequest {
  bool check_contents = 1;
  bool repair = 2;
  int64 store_handle = 100;
}
message VerifyStoreResponse {
  bool errors = 1;
}
