syntax = "proto3";

package nix.store;

import "common.proto";

service StoreService {
  rpc GetUri(GetUriRequest) returns (GetUriResponse);
  rpc GetStoreDir(GetStoreDirRequest) returns (GetStoreDirResponse);
  rpc IsValidPath(IsValidPathRequest) returns (IsValidPathResponse);
  rpc ParseStorePath(ParseStorePathRequest) returns (nix.common.StorePath);
  rpc QueryPathInfo(QueryPathInfoRequest) returns (nix.common.PathInfo);
  rpc QueryPathFromHashPart(QueryPathFromHashPartRequest) returns (QueryPathFromHashPartResponse);
  rpc ComputeFsClosure(ComputeFsClosureRequest) returns (nix.common.StorePathList);
  rpc QueryMissing(QueryMissingRequest) returns (nix.common.MissingInfo);
  rpc QueryDerivationOutputs(QueryDerivationOutputsRequest) returns (nix.common.StorePathList);
  rpc QueryValidDerivers(QueryValidDeriversRequest) returns (nix.common.StorePathList);
  rpc QueryAllValidPaths(QueryAllValidPathsRequest) returns (nix.common.StorePathList);
  rpc QueryReferrers(QueryReferrersRequest) returns (nix.common.StorePathList);
  rpc QuerySubstitutablePaths(QuerySubstitutablePathsRequest) returns (nix.common.StorePathList);
  rpc BuildPathsWithResults(BuildPathsWithResultsRequest) returns (nix.common.BuildResultList);
  rpc ReadDerivation(ReadDerivationRequest) returns (nix.common.Derivation);
  rpc BuildDerivation(BuildDerivationRequest) returns (nix.common.BuildResult);
  rpc FollowLinksToStorePath(FollowLinksToStorePathRequest) returns (nix.common.StorePath);
  rpc AddTempRoot(AddTempRootRequest) returns (AddTempRootResponse);
  rpc FetchFromUrl(FetchFromUrlRequest) returns (nix.common.Input);
  rpc FetchFromAttrs(FetchFromAttrsRequest) returns (nix.common.Input);
}

message GetUriRequest {}
message GetUriResponse {
  string uri = 1;
}

message GetStoreDirRequest {}
message GetStoreDirResponse {
  string dir = 1;
}

message IsValidPathRequest {
  string path = 1;
}
message IsValidPathResponse {
  bool valid = 1;
}

message ParseStorePathRequest {
  string path = 1;
}

message QueryPathInfoRequest {
  string path = 1;
}

message QueryPathFromHashPartRequest {
  string hash_part = 1;
}
message QueryPathFromHashPartResponse {
  optional nix.common.StorePath path = 1;
}

message ComputeFsClosureRequest {
  string path = 1;
  bool flip_direction = 2;
  bool include_outputs = 3;
  bool include_derivers = 4;
}

message QueryMissingRequest {
  repeated string paths = 1;
}

message QueryDerivationOutputsRequest {
  string path = 1;
}

message QueryValidDeriversRequest {
  string path = 1;
}

message QueryAllValidPathsRequest {}

message QueryReferrersRequest {
  string path = 1;
}

message QuerySubstitutablePathsRequest {
  repeated string paths = 1;
}

message BuildPathsWithResultsRequest {
  repeated string paths = 1;
}

message ReadDerivationRequest {
  string path = 1;
}

message BuildDerivationRequest {
  string path = 1;
  int32 build_mode = 2;
}

message FollowLinksToStorePathRequest {
  string path = 1;
}

message AddTempRootRequest {
  string path = 1;
}
message AddTempRootResponse {}

message FetchFromUrlRequest {
  string url = 1;
}

message FetchFromAttrsRequest {
  map<string, nix.common.AttrsValue> attrs = 1;
}