syntax = "proto3";

package nix.worker;

import "common.proto";

service WorkerService {
  rpc Init(InitRequest) returns (InitResponse);
  rpc OpenStore(OpenStoreRequest) returns (OpenStoreResponse);
  rpc CloseStore(CloseStoreRequest) returns (CloseStoreResponse);
  rpc GetVerbosity(GetVerbosityRequest) returns (GetVerbosityResponse);
  rpc SetVerbosity(SetVerbosityRequest) returns (SetVerbosityResponse);
  rpc SubscribeLogs(SubscribeLogsRequest) returns (stream nix.common.LogEvent);
  rpc Shutdown(ShutdownRequest) returns (ShutdownResponse);
}

message InitRequest {
  string store_uri = 1;
  optional string nix_conf = 2;
  map<string, string> settings = 3;
  repeated string experimental_features = 4;
  repeated nix.common.PrimOpSpec primops = 5;
  optional bool pure_eval = 6;
  optional bool restrict_eval = 7;
  repeated string allowed_uris = 8;
  optional nix.common.LogLevel verbosity = 9;
  repeated string nix_path = 10;
  bool load_config = 11;
}

message InitResponse {
  string status = 1;
}

message SubscribeLogsRequest {
  int64 request_id = 1;
}

message OpenStoreRequest {
  string uri = 1;
}
message OpenStoreResponse {
  int64 store_handle = 1;
  string uri = 2;
  string store_dir = 3;
}

message CloseStoreRequest {
  int64 store_handle = 1;
}
message CloseStoreResponse {}

message GetVerbosityRequest {}
message GetVerbosityResponse {
  nix.common.LogLevel verbosity = 1;
}

message SetVerbosityRequest {
  nix.common.LogLevel verbosity = 1;
}
message SetVerbosityResponse {
  nix.common.LogLevel verbosity = 1;
}

message ShutdownRequest {}
message ShutdownResponse {}
