#pragma once

#define NANOPYNIX_NIX_VERSION "@NIX_STORE_VERSION@"

#cmakedefine01 NANOPYNIX_NIX_LOGGER_IS_UNIQUE_PTR
#cmakedefine01 NANOPYNIX_HAVE_BUILD_RESULT_SUM
#cmakedefine01 NANOPYNIX_HAVE_EVALSTATE_MEM
