[build-system]
requires = ["scikit-build-core >=0.10"]
build-backend = "scikit_build_core.build"

[project]
name = "nanopynix-bindings"
version = "0.1.0"
description = "nanobind-based Python bindings for Nix (compiled extensions)"
authors = [{ name = "nanopynix contributors" }]
requires-python = ">=3.10"
classifiers = [
  "License :: OSI Approved :: GNU Lesser General Public License v2 or later (LGPLv2+)",
  "Programming Language :: Python :: 3",
  "Programming Language :: C++",
]

[project.urls]
Homepage = "https://github.com/lillecarl/nanopynix"

[tool.scikit-build]
minimum-version = "build-system.requires"
wheel.platlib = false
cmake.define.BUILD_UTIL = "ON"
cmake.define.BUILD_STORE = "ON"
cmake.define.BUILD_EXPR = "ON"
cmake.define.BUILD_FETCHERS = "ON"
cmake.define.BUILD_FLAKE = "ON"
cmake.define.BUILD_MAIN = "ON"
