name: CI

on:
  push:
  schedule:
    - cron: "17 3 * * *"
  workflow_dispatch:

jobs:
  test:
    if: github.event_name != 'schedule'
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - uses: nixbuild/nix-quick-install-action@v35

      - uses: cachix/cachix-action@v17
        with:
          name: lillecarl
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Build all supported Nix versions
        run: nix build .#nanopynix-all-tests --print-build-logs --print-out-paths

      - name: Test all supported Nix versions
        run: nix run .#nanopynix-all-tests --print-build-logs -- --verbose --tb=short  -rsxXfE --run-temp-store-builds

  update-lockfile:
    if: github.event_name == 'schedule'
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main

      - uses: nixbuild/nix-quick-install-action@v35

      - uses: cachix/cachix-action@v17
        with:
          name: lillecarl
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Update flake inputs
        run: nix flake update

      - name: Build all supported Nix versions
        run: nix build .#nanopynix-all-tests --print-build-logs --print-out-paths

      - name: Test all supported Nix versions
        run: nix run .#nanopynix-all-tests --print-build-logs -- --verbose --tb=short  -rsxXfE --run-temp-store-builds

      - uses: step-security/git-auto-commit-action@v7
        with:
          commit_message: "nix flake update"
